.build:
  stage: build
  image: $NODE_IMAGE
  cache:
    key:
      prefix: npm
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - ${DIST_DIR}

npm preview:
  extends: .build
  only:
    refs:
      - branches
  except:
    refs:
      - tags
  needs:
    - vendor preview

npm release:
  extends: .build
  only:
    refs:
      - tags
  needs:
    - vendor production
