service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
application:
  track: stable
  env: production

resourcesProd:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi
resourcesDev:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

deployment:
  replicas:
    prod: 1
    dev: 1
